const enCA = [
  {
    'id': '10',
    'name': 'Fix Tail Light',
    'category': '1',
    'price': 500.0,
    'taxAndFee': 50.0,
    'isSelected': true,
    'parentServiceId': null,
    'serviceAdvisorComments': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'comment': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'imageUrl': './images/tail-lights.webp',
    'iconUrl': null,
    'isHighlighted': false,
    'declinedReasonId': -1,
    'laborMatrixPayment': 'None',
    'laborMatrixPaymentTranslations': null
  },
  {
    'id': '11',
    'name': 'Replace Windshield Wipers',
    'category': '1',
    'price': 0.0,
    'taxAndFee': 0.0,
    'isSelected': false,
    'parentServiceId': null,
    'serviceAdvisorComments': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'comment': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'imageUrl': './images/windshield-wipers.jpg',
    'iconUrl': null,
    'isHighlighted': false,
    'declinedReasonId': -1,
    'laborMatrixPayment': 'Warranty',
    'laborMatrixPaymentTranslations': 'Covered by warranty'
  },
  {
    'id': '22',
    'name': 'Replace Air Filter',
    'category': '2',
    'price': 100.0,
    'taxAndFee': 15.0,
    'isSelected': true,
    'parentServiceId': null,
    'serviceAdvisorComments': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'comment': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'imageUrl': './images/air-filter.jpg',
    'iconUrl': null,
    'isHighlighted': false,
    'declinedReasonId': -1,
    'laborMatrixPayment': 'NA',
    'laborMatrixPaymentTranslations': null
  },
  {
    'id': '23',
    'name': 'Replace Cooling System Hoses',
    'category': '2',
    'price': 40.0,
    'taxAndFee': 20.0,
    'isSelected': false,
    'parentServiceId': null,
    'serviceAdvisorComments': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'comment': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'imageUrl': './images/cooling-system-hoses.jpg',
    'iconUrl': null,
    'isHighlighted': false,
    'declinedReasonId': -1,
    'laborMatrixPayment': 'None',
    'laborMatrixPaymentTranslations': null
  },
  {
    'id': '30',
    'name': 'Check Rear Shocks',
    'category': '3',
    'price': 0.0,
    'taxAndFee': 0.0,
    'isSelected': false,
    'parentServiceId': null,
    'serviceAdvisorComments': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'comment': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'imageUrl': null,
    'iconUrl': null,
    'isHighlighted': false,
    'declinedReasonId': -1,
    'laborMatrixPayment': 'None',
    'laborMatrixPaymentTranslations': null
  },
  {
    'id': '31',
    'name': 'Adjust Tire Rotation',
    'category': '3',
    'price': 0.0,
    'taxAndFee': 0.0,
    'isSelected': false,
    'parentServiceId': null,
    'serviceAdvisorComments': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'comment': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'imageUrl': 'https://via.placeholder.com/479x356.png?text=Safety%20Concerns%20Service%2031',
    'iconUrl': null,
    'isHighlighted': false,
    'declinedReasonId': -1,
    'laborMatrixPayment': 'None',
    'laborMatrixPaymentTranslations': null
  },
  {
    'id': '41',
    'name': 'Check Differential For Leaks',
    'category': '4',
    'price': 30.0,
    'taxAndFee': 20.0,
    'isSelected': false,
    'parentServiceId': null,
    'serviceAdvisorComments': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'comment': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'imageUrl': 'https://via.placeholder.com/479x356.png?text=Safety%20Concerns%20Service%2013',
    'iconUrl': null,
    'isHighlighted': false,
    'declinedReasonId': -1,
    'laborMatrixPayment': 'None',
    'laborMatrixPaymentTranslations': null
  },
  {
    'id': '61',
    'name': 'Test Battery Capacity (en-CA)',
    'category': '6',
    'price': 0.0,
    'taxAndFee': 0.0,
    'isSelected': false,
    'parentServiceId': null,
    'serviceAdvisorComments': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'comment': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'imageUrl': './images/battery.jpg',
    'iconUrl': null,
    'isHighlighted': false,
    'declinedReasonId': -1,
    'laborMatrixPayment': 'Free',
    'laborMatrixPaymentTranslations': 'Free'
  },
  {
    'id': '62',
    'name': 'Test Battery Capacity (en-CA)',
    'category': '6',
    'price': 0.0,
    'taxAndFee': 0.0,
    'isSelected': false,
    'parentServiceId': '61',
    'serviceAdvisorComments': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'comment': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'imageUrl': './images/battery.jpg',
    'iconUrl': null,
    'isHighlighted': false,
    'declinedReasonId': -1,
    'laborMatrixPayment': 'Free',
    'laborMatrixPaymentTranslations': 'Free'
  },
  {
    'id': '81',
    'name': 'Check Muffler Noise',
    'category': '8',
    'price': 55.0,
    'taxAndFee': 20.0,
    'isSelected': false,
    'parentServiceId': null,
    'serviceAdvisorComments': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'comment': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'imageUrl': 'https://via.placeholder.com/544x532.png?text=Safety%20Concerns%20Service%2015',
    'iconUrl': null,
    'isHighlighted': false,
    'declinedReasonId': -1,
    'laborMatrixPayment': 'None',
    'laborMatrixPaymentTranslations': null
  },
  {
    'id': '82',
    'name': 'Check Muffler Noise',
    'category': '81',
    'price': 55.0,
    'taxAndFee': 20.0,
    'isSelected': false,
    'parentServiceId': null,
    'serviceAdvisorComments': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'comment': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'imageUrl': 'https://via.placeholder.com/544x532.png?text=Safety%20Concerns%20Service%2015',
    'iconUrl': null,
    'isHighlighted': false,
    'declinedReasonId': -1,
    'laborMatrixPayment': 'None',
    'laborMatrixPaymentTranslations': null
  }
]

const frCA = [
  {
    'id': '10',
    'name': 'FR: Fix Tail Light',
    'category': '1',
    'price': 500.0,
    'taxAndFee': 50.0,
    'isSelected': true,
    'parentServiceId': null,
    'serviceAdvisorComments': 'FR: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'comment': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'imageUrl': './images/tail-lights.webp',
    'iconUrl': null,
    'isHighlighted': false,
    'declinedReasonId': -1,
    'laborMatrixPayment': 'None',
    'laborMatrixPaymentTranslations': null
  },
  {
    'id': '11',
    'name': 'FR: Replace Windshield Wipers',
    'category': '1',
    'price': 0.0,
    'taxAndFee': 0.0,
    'isSelected': false,
    'parentServiceId': null,
    'serviceAdvisorComments': 'FR: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'comment': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'imageUrl': './images/windshield-wipers.jpg',
    'iconUrl': null,
    'isHighlighted': false,
    'declinedReasonId': -1,
    'laborMatrixPayment': 'Warranty',
    'laborMatrixPaymentTranslations': 'FR: Covered by warranty'
  },
  {
    'id': '22',
    'name': 'FR: Replace Air Filter',
    'category': '2',
    'price': 100.0,
    'taxAndFee': 15.0,
    'isSelected': true,
    'parentServiceId': null,
    'serviceAdvisorComments': 'FR: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'comment': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'imageUrl': './images/air-filter.jpg',
    'iconUrl': null,
    'isHighlighted': false,
    'declinedReasonId': -1,
    'laborMatrixPayment': 'NA',
    'laborMatrixPaymentTranslations': null
  },
  {
    'id': '23',
    'name': 'FR: Replace Cooling System Hoses',
    'category': '2',
    'price': 40.0,
    'taxAndFee': 20.0,
    'isSelected': false,
    'parentServiceId': null,
    'serviceAdvisorComments': 'FR: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'comment': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'imageUrl': './images/cooling-system-hoses.jpg',
    'iconUrl': null,
    'isHighlighted': false,
    'declinedReasonId': -1,
    'laborMatrixPayment': 'None',
    'laborMatrixPaymentTranslations': null
  },
  {
    'id': '30',
    'name': 'FR: Check Rear Shocks',
    'category': '3',
    'price': 0.0,
    'taxAndFee': 0.0,
    'isSelected': false,
    'parentServiceId': null,
    'serviceAdvisorComments': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'comment': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'imageUrl': null,
    'iconUrl': null,
    'isHighlighted': false,
    'declinedReasonId': -1,
    'laborMatrixPayment': 'None',
    'laborMatrixPaymentTranslations': null
  },
  {
    'id': '31',
    'name': 'FR: Adjust Tire Rotation',
    'category': '3',
    'price': 0.0,
    'taxAndFee': 0.0,
    'isSelected': false,
    'parentServiceId': null,
    'serviceAdvisorComments': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'comment': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'imageUrl': 'https://via.placeholder.com/479x356.png?text=Safety%20Concerns%20Service%2031',
    'iconUrl': null,
    'isHighlighted': false,
    'declinedReasonId': -1,
    'laborMatrixPayment': 'None',
    'laborMatrixPaymentTranslations': null
  },
  {
    'id': '41',
    'name': 'FR: Check Differential For Leaks',
    'category': '4',
    'price': 30.0,
    'taxAndFee': 20.0,
    'isSelected': false,
    'parentServiceId': null,
    'serviceAdvisorComments': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'comment': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'imageUrl': 'https://via.placeholder.com/479x356.png?text=Safety%20Concerns%20Service%2013',
    'iconUrl': null,
    'isHighlighted': false,
    'declinedReasonId': -1,
    'laborMatrixPayment': 'None',
    'laborMatrixPaymentTranslations': null
  },
  {
    'id': '61',
    'name': 'FR: Test Battery Capacity (fr-CA)',
    'category': '6',
    'price': 0.0,
    'taxAndFee': 0.0,
    'isSelected': false,
    'parentServiceId': null,
    'serviceAdvisorComments': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'comment': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'imageUrl': './images/battery.jpg',
    'iconUrl': null,
    'isHighlighted': false,
    'declinedReasonId': -1,
    'laborMatrixPayment': 'Free',
    'laborMatrixPaymentTranslations': 'FR-Free'
  },
  {
    'id': '62',
    'name': 'FR: Test Battery Capacity (fr-CA)',
    'category': '6',
    'price': 0.0,
    'taxAndFee': 0.0,
    'isSelected': false,
    'parentServiceId': '61',
    'serviceAdvisorComments': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'comment': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'imageUrl': './images/battery.jpg',
    'iconUrl': null,
    'isHighlighted': false,
    'declinedReasonId': -1,
    'laborMatrixPayment': 'Free',
    'laborMatrixPaymentTranslations': 'FR-Free'
  },
  {
    'id': '81',
    'name': 'FR: Check Muffler Noise',
    'category': '8',
    'price': 55.0,
    'taxAndFee': 20.0,
    'isSelected': false,
    'parentServiceId': null,
    'serviceAdvisorComments': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'comment': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'imageUrl': 'https://via.placeholder.com/544x532.png?text=Safety%20Concerns%20Service%2015',
    'iconUrl': null,
    'isHighlighted': false,
    'declinedReasonId': -1,
    'laborMatrixPayment': 'None',
    'laborMatrixPaymentTranslations': null
  },
  {
    'id': '82',
    'name': 'FR: Check Muffler Noise',
    'category': '81',
    'price': 55.0,
    'taxAndFee': 20.0,
    'isSelected': false,
    'parentServiceId': null,
    'serviceAdvisorComments': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'comment': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'imageUrl': 'https://via.placeholder.com/544x532.png?text=Safety%20Concerns%20Service%2015',
    'iconUrl': null,
    'isHighlighted': false,
    'declinedReasonId': -1,
    'laborMatrixPayment': 'None',
    'laborMatrixPaymentTranslations': null
  }
]

const esMX = [
  {
    'id': '10',
    'name': 'ES: Fix Tail Light',
    'category': '1',
    'price': 500.0,
    'taxAndFee': 50.0,
    'isSelected': true,
    'parentServiceId': null,
    'serviceAdvisorComments': 'ES: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'comment': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'imageUrl': './images/tail-lights.webp',
    'iconUrl': null,
    'isHighlighted': false,
    'declinedReasonId': -1,
    'laborMatrixPayment': 'None',
    'laborMatrixPaymentTranslations': null
  },
  {
    'id': '11',
    'name': 'ES: Replace Windshield Wipers',
    'category': '1',
    'price': 0.0,
    'taxAndFee': 0.0,
    'isSelected': false,
    'parentServiceId': null,
    'serviceAdvisorComments': 'ES: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'comment': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'imageUrl': './images/windshield-wipers.jpg',
    'iconUrl': null,
    'isHighlighted': false,
    'declinedReasonId': -1,
    'laborMatrixPayment': 'Warranty',
    'laborMatrixPaymentTranslations': 'ES: Covered by warranty'
  },
  {
    'id': '22',
    'name': 'ES: Replace Air Filter',
    'category': '2',
    'price': 100.0,
    'taxAndFee': 15.0,
    'isSelected': true,
    'parentServiceId': null,
    'serviceAdvisorComments': 'ES: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'comment': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'imageUrl': './images/air-filter.jpg',
    'iconUrl': null,
    'isHighlighted': false,
    'declinedReasonId': -1,
    'laborMatrixPayment': 'NA',
    'laborMatrixPaymentTranslations': null
  },
  {
    'id': '23',
    'name': 'ES: Replace Cooling System Hoses',
    'category': '2',
    'price': 40.0,
    'taxAndFee': 20.0,
    'isSelected': false,
    'parentServiceId': null,
    'serviceAdvisorComments': 'ES: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'comment': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'imageUrl': './images/cooling-system-hoses.jpg',
    'iconUrl': null,
    'isHighlighted': false,
    'declinedReasonId': -1,
    'laborMatrixPayment': 'None',
    'laborMatrixPaymentTranslations': null
  },
  {
    'id': '30',
    'name': 'ES: Check Rear Shocks',
    'category': '3',
    'price': 0.0,
    'taxAndFee': 0.0,
    'isSelected': false,
    'parentServiceId': null,
    'serviceAdvisorComments': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'comment': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'imageUrl': null,
    'iconUrl': null,
    'isHighlighted': false,
    'declinedReasonId': -1,
    'laborMatrixPayment': 'None',
    'laborMatrixPaymentTranslations': null
  },
  {
    'id': '31',
    'name': 'ES: Adjust Tire Rotation',
    'category': '3',
    'price': 0.0,
    'taxAndFee': 0.0,
    'isSelected': false,
    'parentServiceId': null,
    'serviceAdvisorComments': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'comment': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'imageUrl': 'https://via.placeholder.com/479x356.png?text=Safety%20Concerns%20Service%2031',
    'iconUrl': null,
    'isHighlighted': false,
    'declinedReasonId': -1,
    'laborMatrixPayment': 'None',
    'laborMatrixPaymentTranslations': null
  },
  {
    'id': '41',
    'name': 'ES: Check Differential For Leaks',
    'category': '4',
    'price': 30.0,
    'taxAndFee': 20.0,
    'isSelected': false,
    'parentServiceId': null,
    'serviceAdvisorComments': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'comment': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'imageUrl': 'https://via.placeholder.com/479x356.png?text=Safety%20Concerns%20Service%2013',
    'iconUrl': null,
    'isHighlighted': false,
    'declinedReasonId': -1,
    'laborMatrixPayment': 'None',
    'laborMatrixPaymentTranslations': null
  },
  {
    'id': '61',
    'name': 'ES: Test Battery Capacity (es-mx)',
    'category': '6',
    'price': 0.0,
    'taxAndFee': 0.0,
    'isSelected': false,
    'parentServiceId': null,
    'serviceAdvisorComments': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'comment': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'imageUrl': './images/battery.jpg',
    'iconUrl': null,
    'isHighlighted': false,
    'declinedReasonId': -1,
    'laborMatrixPayment': 'Free',
    'laborMatrixPaymentTranslations': 'ES-Free'
  },
  {
    'id': '62',
    'name': 'ES: Test Battery Capacity (es-mx)',
    'category': '6',
    'price': 0.0,
    'taxAndFee': 0.0,
    'isSelected': false,
    'parentServiceId': '61',
    'serviceAdvisorComments': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'comment': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'imageUrl': './images/battery.jpg',
    'iconUrl': null,
    'isHighlighted': false,
    'declinedReasonId': -1,
    'laborMatrixPayment': 'Free',
    'laborMatrixPaymentTranslations': 'ES-Free'
  },
  {
    'id': '81',
    'name': 'ES: Check Muffler Noise',
    'category': '8',
    'price': 55.0,
    'taxAndFee': 20.0,
    'isSelected': false,
    'parentServiceId': null,
    'serviceAdvisorComments': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'comment': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'imageUrl': 'https://via.placeholder.com/544x532.png?text=Safety%20Concerns%20Service%2015',
    'iconUrl': null,
    'isHighlighted': false,
    'declinedReasonId': -1,
    'laborMatrixPayment': 'None',
    'laborMatrixPaymentTranslations': null
  },
  {
    'id': '82',
    'name': 'ES: Check Muffler Noise',
    'category': '81',
    'price': 55.0,
    'taxAndFee': 20.0,
    'isSelected': false,
    'parentServiceId': null,
    'serviceAdvisorComments': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'comment': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'imageUrl': 'https://via.placeholder.com/544x532.png?text=Safety%20Concerns%20Service%2015',
    'iconUrl': null,
    'isHighlighted': false,
    'declinedReasonId': -1,
    'laborMatrixPayment': 'None',
    'laborMatrixPaymentTranslations': null
  }
]

export default {
  'en-CA': enCA,
  'en-US': enCA,
  'fr-CA': frCA,
  'es-MX': esMX
}
